# Generated by Django 4.1.5 on 2023-01-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Tags',
            field=models.ManyToManyField(to='Blog.tag'),
        ),
    ]
